---
- hosts: local  # hosts中指定
  remote_user: fabric  # 如果和当前用户一样，则无需指定
  sudo: yes
  tasks:
      - name: whoami
        copy: src=/etc/hosts dest=/home/fabric/hosts.dest  #  本地拷贝到远端
        notify:  # 如果copy执行完之后~/hosts.dest文件发生了变化，则执行
            - clear copy  # 调用handler
  handlers:
      - name: clear copy
        shell: 'mv /home/fabric/hosts.dest /home/fabric/hosts.del'  # 假装删除